"""
Step 3: answer the project's questions with simple calculations.

No machine learning is used. The questions are about describing what
happened and comparing it with targets, so plain arithmetic is the most
honest and explainable tool.
"""

import pandas as pd

import config


def load_clean() -> pd.DataFrame:
    """Read the cleaned data and remove rows flagged as copied."""
    if not config.CLEAN_DATA_FILE.exists():
        raise FileNotFoundError(
            f"{config.CLEAN_DATA_FILE} not found. Run  python src/clean_data.py  first."
        )
    df = pd.read_csv(config.CLEAN_DATA_FILE)
    return df[~df["repeated_from_previous_year"]].copy()


def latest_year_rows(df: pd.DataFrame) -> pd.DataFrame:
    """Return one row per country: its most recent year of reliable data."""
    idx = df.groupby("country")["year"].idxmax()
    return df.loc[idx].reset_index(drop=True)


def summary_table(df: pd.DataFrame) -> pd.DataFrame:
    """
    One row per GCC country comparing START_YEAR with the latest year.
    """
    rows = []
    for country in config.GCC_COUNTRIES:
        c = df[df["country"] == country]
        first = c[c["year"] == c["year"].min()].iloc[0]
        last = c[c["year"] == c["year"].max()].iloc[0]
        rows.append(
            {
                "country": config.SHORT_NAMES[country],
                "latest_year": int(last["year"]),
                "low_carbon_share_%": round(last["low_carbon_share_elec"], 1),
                "renewables_share_%": round(last["renewables_share_elec"], 1),
                "nuclear_share_%": round(last["nuclear_share_elec"], 1),
                "kwh_per_person": round(last["per_capita_electricity"]),
                f"co2_g_per_kwh_{int(first['year'])}": round(first["carbon_intensity_elec"]),
                "co2_g_per_kwh_latest": round(last["carbon_intensity_elec"]),
                "generation_growth_%": round(
                    100 * (last["electricity_generation"] / first["electricity_generation"] - 1)
                ),
            }
        )
    return pd.DataFrame(rows).sort_values("low_carbon_share_%", ascending=False)


def recent_pace(series: pd.Series, years: pd.Series, window: int) -> float:
    """
    Average change per year over the last `window` years.

    Example: 2.0% in 2021 and 5.0% in 2024 -> (5.0 - 2.0) / 3 = 1.0 point per year.
    """
    end_year = years.max()
    start_year = end_year - window
    start_value = series[years == start_year]
    end_value = series[years == end_year]
    if start_value.empty or end_value.empty:
        raise ValueError(f"Need data for both {start_year} and {end_year}.")
    return (end_value.iloc[0] - start_value.iloc[0]) / window


def target_check(df: pd.DataFrame) -> pd.DataFrame:
    """
    For each official target: where is the country now, how fast must it
    move to reach the target, and how fast has it moved recently?
    """
    rows = []
    for t in config.TARGETS:
        c = df[df["country"] == t["country"]]
        latest_year = int(c["year"].max())
        current = c.loc[c["year"] == latest_year, t["column"]].iloc[0]
        years_left = t["target_year"] - latest_year
        required = (t["target_percent"] - current) / years_left
        pace = recent_pace(c[t["column"]], c["year"], config.PACE_WINDOW_YEARS)
        # If recent pace simply continued (a straight line, NOT a forecast):
        straight_line = current + pace * years_left
        rows.append(
            {
                "country": config.SHORT_NAMES[t["country"]],
                "measure": t["column"],
                "target": f"{t['target_percent']:.0f}% by {t['target_year']}",
                "latest_year": latest_year,
                "current_%": round(current, 1),
                "required_pace_pts_per_year": round(required, 2),
                f"recent_pace_pts_per_year_{config.PACE_WINDOW_YEARS}y": round(pace, 2),
                "if_recent_pace_continued_%": round(min(straight_line, 100), 1),
                "on_track_at_recent_pace": pace >= required,
            }
        )
    return pd.DataFrame(rows)


def write_findings(summary: pd.DataFrame, targets: pd.DataFrame) -> None:
    """Save the tables as a Markdown file that GitHub displays nicely."""
    text = [
        "# Findings (generated by run_all.py — do not edit by hand)",
        "",
        "## Summary by country",
        "",
        summary.to_markdown(index=False),
        "",
        "## Target check",
        "",
        "`required_pace` = percentage points per year needed from the latest year "
        "to reach the target.  `recent_pace` = average change per year over the last "
        f"{config.PACE_WINDOW_YEARS} years.  The straight-line value is a simple "
        "'what if nothing changes' calculation, **not a forecast**.",
        "",
        targets.to_markdown(index=False),
        "",
    ]
    out = config.REPORTS_DIR / "findings.md"
    out.write_text("\n".join(text), encoding="utf-8")
    print(f"Saved {out}")
